### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [mitxela/ddc-oled#1]
Hello!

I found your project from https://hackaday.com/2022/04/01/making-your-own-technically-hdmi-oled-monitor/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

Also, please copy MIT license from https://github.com/zorvios/PyXCursor/blob/master/LICENSE into your directory with PyXCursor.

**Comment by mitxela** [comment]
Sure. Sorry wasn't really expecting anyone to _want_ to use this.

**Comment by vazhnov** [comment]
Maybe someone will improve it, so an opensource license is important.
MIT license — great!
Thank you, @mitxela!
